project:
  type: book

book:
  title: "WildHealthDat"
  author: "Diego Montecino-Latorre"
  date: "7/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - project.qmd
    - surveillance_objective.qmd
    - field_activity.qmd
    - location.qmd
    - incident.qmd
    - source_source_records.qmd
    - specimen.qmd
    - data_dictionary.qmd
  # search: true
  repo-url: https://github.com/dmontecino/WH_Database
  repo-actions: [edit]
  downloads: [pdf, epub]

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

