project:
  type: book
  output-dir: _book

book:
  title: "WildHealthDB"
  author: "Diego Montecino-Latorre"
  date: "11/3/2024"
  chapters:
    - index.qmd
    # - intro.qmd
    # - project.qmd
    # - surveillance_objective.qmd
    # - field_activity.qmd
    # - location.qmd
    # - incident.qmd
    # - source_source_records.qmd
    # - specimen.qmd
    # - diagnostics.qmd
    - data_model.qmd
    - data_dictionary.qmd
    - manual.qmd
  search:
    type: textbox
    location: sidebar
  repo-url: https://github.com/dmontecino/WH_Database
  #repo-actions: [edit]
  downloads: [pdf]
  #output-file: "WildHealthDat.pdf"
  #output-file: "puto_libro"
# file:
#   format: "pdf"
# #   url: "https://example.com/book.pdf"

toc-title: On this page

# bibliography: references.bib

format:
  html:
    theme:  
      - cerulean
    # number-depth: 9
    page-layout: full
  pdf:
    documentclass: scrreprt
  # epub:
  #   toc:
  #     true
  #   lang:
  #     en-US
  #   date:
  #     "2023-03-01"

# editor: visual

execute:
  freeze: auto
