project:
  type: book

book:
  title: "WildHealthDat"
  author: "Diego Montecino-Latorre"
  date: "7/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - project.qmd
    - surveillance_objective.qmd
    - Wildlife_Health_Database_Rules.qmd
    - data_dictionary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

