## Complexities

For example, rodents trapped in the same Event may be sampled using the same methodology but tested for coronaviruses and Rickettsia *sp*. In this scenario, two Surveillance Activities should be assigned to the Field Visits, Locations, Events, Source Records, and Specimens. Diagnostics for either group of pathogens and the corresponding Diagnosis should only get a single Surveillance Activity. 

Another exception to this rule is the collection of Specimens from Sources that belonged to other Surveillance Activities. For example, marked rodents that were released, and later captured and tested for a specific hazard under Surveillance Activity A that were captured and sampled during Surveillance Activity B months later. In this case, these rodents will be part of two Surveillance Activities (A and B).

Another exception occurs when Specimens were collected during past surveillance efforts but are included in new surveillance initiatives. For instance, using pangolin Specimens collected by veterinarians in 2017 and tested for Salmonella sps. which are then tested in 2023 for SARS-CoV-2. In this case, the latter Surveillance Activity is assigned to the Specimens being tested (as a second Surveillance Activity) and to the SARS-CoV-2 Diagnostics and Diagnosis. Therefore, these Specimens should have two Surveillance Objectives. The first one corresponds to the original Surveillance Activity that lead to their collection and the second one corresponds to the Surveillance Activity testing them for SARS-CoV-2. The Source (pangolin) and the corresponding Record should keep a single Surveillance Activity.

Moreover, Necropsies might be conducted as part of a secondary Surveillance Activity (on a Carcass that was collected under other Surveillance Activity) or new Specimens could be created from a previously unused Carcass as part of a new Surveillance Activity. In this case, the new data (Necropsy and Specimens) should receive the second Surveillance Activity only. Diagnostics using the new Specimens should receive the second Surveillance Activity only. The Carcass should receive the Surveillance Activity that lead to its collection only.

Finally, the health of the same animal could be assessed under different Surveillance Activities. For example, a ranger that finds a sick animal in a specific date and assess it health and potential cause of disease. Then, the animal is taken to a rehabilitation center where its health is assessed again at admission and samples are collected for testing. Finally, the animal health at the rehabilitation center can be assessed again later and more sampled could be taken in order to learn what pathogens are circulating within the facility. This animal has been part of three potential Surveillance Activities, each with different target populations and methods. To track the path of this animal, each Field Visit (ranger patrolling, the admission at the rehabilitation center, and the sampling at admission) should be part of one Surveillance Activity only. The Locations within each Field Activity (a protected area, the rehabilitation center, and the rehabilitation center), should be part of the first, the second, and third Surveillance Activities only. Each Event at each Location, (when it was found originally in the protected area, examined at admission to the rehabilitation center, and then sampled after admission) should be part of a single Surveillance Activity, 


it should receive the three Surveillance Activities. Each Event (when it was found originally, examined at admission to the rehabilitation center, and then sampled after admission) should be part of a single Surveillance Activity, the Locations (a protected area and the rehabilitation center), should be part of one and two Surveillance Activities, respectively correspondingly, 

Therefore, Surveillance Activities can be interconnected through the reuse of Specimens or expanding the data generated by previous Surveillance Activities. These connections will be evident in the exported data, where each component with multiple Surveillance Activities (e.g., Specimen) will be represented by one row per Surveillance Activity. 





Locations can be clustered in larger nested or non-nested spatial units if needed. For a detail explanation, see "Clustering of Locations, Events, and Source Records" section below.


