**Diagnostics in the data model encompass various techniques used to identify hazards (biological, chemical, physical) or physiological problems in either Source Records of Animal and Group Sources or Specimens obtained from Source Records of any type**. Diagnostics conducted directly in Group and Animals Sources can include general body condition (Group or Animal Source), the width of body fat (Group or Animal Source), an ultrasound (Animal Source). Diagnostics can range from advanced techniques such as metagenomics to basic observations of body condition. Whatever the Diagnostic methods used are, they must be reported in the metadata of the Surveillance Activity.

In the data model, Diagnostics can be conducted in a Laboratory or similar (see Laboratory below) but it is also possible to include field-base assays. Diagnostics can also be conducted by an individual (ranger, hunter, researcher, biologist, etc.) when they involve external or simple observations such as the body condition of an animal to assess a nutrition related hazard. 

In the data model, it is considered that each Diagnostic is designed for a specific targeted hazard, such as a viral family or a particular virus species and, therefore, each Diagnostic - Hazard is a Diagnostic method. 

Diagnostics include the type, method, and result. The type of Diagnostic refers to a general category of diagnostic techniques, such as histopathology, serology, imaging, molecular, clinical. Within each type, there are specific methods available, such as biopsy, ELISA assays, X-rays, PCR, or the width of fat in a herd, respectively. In the data model, **each Diagnostic has a unit of measurement that can either be qualitative or quantitative. The result of the diagnostic is reported as a value of those units**. For example, an agglutination test can report the minimum dilution that causes observable agglutination. A PCR can be reported as presence of bands compatible with the targeted genome sequence or genetic sequence compatible with targeted organism if sequencing followed the genetic sequence amplification. **The interpretation of a Diagnostic (positive, negative, undetermined) corresponds to an "Interpretation" of the Diagnostic ** (see Interpretation in Complexities below). Other properties of a Diagnostic include the Diagnostic ID, Diagnostic Code, Diagnostic Cross Reference ID, Diagnostic Cross Reference Origin, among others (see Data Dictionary).

<!-- **It is ideal to include supporting information to each Diagnostic, such as digital images or files to corroborate the entered result in the database**.  -->

#### Diagnostic Products as Specimens

In the data model, **Diagnostics can produce "Diagnostic Products" that are then considered a Specimen**.  Diagnostic products as Specimens can be traced with respect to their storage, the quantities available, and any exportation process (See Exportation in Complexities). Furthermore, Specimens from Diagnostics Products can be used as in other Diagnostics (see Specimens above). For example, cDNA used in a new PCR essay. Basically the data model accepts a new Specimen whose origin is a Diagnostic Product with the corresponding type and its origin is a Diagnostic instead of one or multiple Source Records, or other Specimens (See Specimens above).

 
