# Incidents {.unnumbered}

An Incident is a specific wildlife health event at specific longitude and latitude and that occurs in a specific date.

The definition of what a wildlife health event (and therefore of the 'Incident' component) depends on the Surveillance Objective methodology. In targeted surveillance efforts, an Incident could imply just healthy animals sampled in a specific time-space unit to test them for the targeted hazard. Non-sampled individuals, injured, sick, or dead may or may not be included as part of the Incident. If samples are collected from a river, then the 'Incident' can be equivalent to the location where water is extracted at. For the surveillance of vector-borne diseases, an 'Incident' could be a point in time and space where one to several traps for vectors have been placed. For scanning surveillance, an 'Incident' could require the presence of at least one injured, sick, or dead animal, or an stranded individual. The 'Incident' can also include the healthy individuals found nearby.

In the case of beached fish, an Incident could represent each dead fish in one extreme. On the other extreme an Incident can represent to the full count of dead fish across the beach as a single point in time and space. None of these strategies seem ideal. The former, for logistic purposes and the latter, for the loss of valuable information (distribution of the dead fish across the beach). So an Incident should represent a unit in between.

Similarly, an entire market could represent a 'Location' and a single 'Incident' at the same time. This Incident can gather data from several vendors, cages, and animals within cages. On the other hand, a market could be a 'Location' and each vendor within the market could be an 'Incident'. Finally, a structured study can involve several levels of hierarchy and one of them receives the temporo-spatial coordinate. Another similar structured study (zone, grid, area, trap, etc.) might provide the spatial coordinate to a different unit (for example the area in one case and the trap in another case). Therefore, an Incident can represent a wide range of units depending on the methodology used to record health ata. For this reason, it is necessary to provide flexibility to what an Incident is per surveillance design and it is also necessary to request and explicitly declare what an Incident represents as part of its data.

In the market example or structured studies, it could be desired to group Incidents more specifically than under the general 'Location'. For example, a market can be a 'Location' and each cage could represent an 'Incident'. It is possible that users want to group cages by vendors and vendors by area within the market, Similarly, it is possible that in a structured study the 'Incident' represents a trap, and the researchers want to group traps these Incidents by area, grid cell, zone, and season. For this reason, the database contains several 'Incident' tags to group them temporally, spatially, or both in a finer scale than Location. Specific tags can be requested by users.

Incidents must have at least one Source Record from one Source type (see below) and as many Source Records of any type as needed (depending on what is found/recorded in each specific Incident and what is the interest of the corresponding Surveillance Objective).
