## Presentation {.unnumbered}

```{r, echo=FALSE}

htmltools::div(
  htmltools::a(
    href = "https://www.whin.org", target = "_blank",
    htmltools::img(src = knitr::image_uri("Pictures_and_diagrams/WHINlogo.png"),
                   alt = 'WHIN logo',  
                   style = "position: fixed; right: 10px; top: 0%; width: 220px;")
  ),
  htmltools::a(
    href = "https://www.wcs.org", target = "_blank",
    htmltools::img(src = knitr::image_uri("Pictures_and_diagrams/WCS_LOGOTYPE.png"),
                   alt = 'WCS logo',  
                   style = "position: fixed; right: 10px; top: 13%; width: 200px;")
  ),
  htmltools::a(
    href = "https://www.iucn.org/our-union/commissions/world-commission-protected-areas", target = "_blank",
    htmltools::img(src = knitr::image_uri("Pictures_and_diagrams/wcpa-logo.png"),
                   alt = 'WCPA logo',  
                   style = "position: fixed; right: 10px; top: 20%; width: 200px;")
  ),
  htmltools::a(
    href = "https://snappartnership.net/", target = "_blank",
    htmltools::img(src = knitr::image_uri("Pictures_and_diagrams/snapp-logo-250.png"),
                   alt = 'SNAPP logo',  
                   style = "position: fixed; right: 0px; top: 40%; width: 200px; background-color: black;")
  )
)


```

<!-- ## Presentation {.unnumbered} -->

Wildlife health surveillance (WHS) is critical for addressing health hazards that threaten wildlife and undermine One Health. It involves a comprehensive set of activities aimed at continuously and rapidly generating and analyzing information on the health of wildlife and associated hazards to prevent, mitigate, control, or eliminate exposure to these hazards and support population resilience.

WHS systems rely on diverse data, including information on environmental features, animal observations, specimens collected, necropsy findings, and diagnostic test results, generated by many actors through various methodologies targeting different hazards, vectors, and hosts. These diverse data need to be managed properly so they remain safe, secured, centralized, available, standardized, and comprehensible in the short- and long-term. In this manner, WHS data can be rapidly assessed, communicated, and responded to utilizing an evidence-based decision making process.

Despite its relevance, WHS data management is a historical weakness that has impacted the response to health crises and the establishment of One Health surveillance systems. Furthermore, as ~50 % of countries report no WHS, collaborative networks among key in-country partners can be developed to expand its coverage. Efficient data management for this WHS expansion strategy is key to ensure their operation as a functionally cohesive unit.

Well-designed databases promote and facilitate data safety, security, centralization, harmonization, quality, availability, communication, and sharing. Moreover, purpose-built databases are key for improving data governance and the implementation and operation of effective WHS systems.

While a few databases exist, they are private, costly, restricted to specific agencies, or limited in scope. WHS is generally underfunded, limiting the development and maintenance of system-specific databases. In line with this reality, the World Organization for Animal Health (WOAH) recently reported that only 61 % of surveyed countries maintain wildlife health data in a “sustainable and reliable information system” and most WOAH national focal points for wildlife recently expressed the need for a wildlife centralized health national database.

To address this gap, Wildlife Conservation Society (WCS) is coordinating the Wildlife Health Intelligence Network (WHIN), a broad community of practice supporting WHS implementation from local to global scales (https://wildlifehealthintelligence.net/), to develop the WHS purpose-built and accessible web-based **Health and Wildlife Knowledge** (HAWK) database. Rather than serving as another data repository, HAWK functions as a data service that allows users to properly manage WHS data they generate or collate, applying self-defined methodologies to achieve objectives such as pathogen detection or establishing disease freedom.

## Why use HAWK?

HAWK is optimized to meet the needs of public agencies, private organizations, academia, and other interested actors conducting WHS or related monitoring of different hosts, hazards, and diseases, using variable methods, effectively managing diverse data. For example, an organization can structure and centralize data from mortality investigations, opportunistic findings, tested samples from handled or harvested animals, community-based or systematic monitoring (e.g., mortality recorded via iNaturalist, ranger patrols), collated news articles, and research projects using advanced designs (Fig. 2).

HAWK's data structure is compatible with repositories such as the Global Biodiversity Information Facility (GBIF) and WOAH's World Animal Health Information System (WAHIS). Therefore, data in these repositories considered relevant for WHS can be brought into a HAWK account (for a Surveillance Activity), whilst data in a HAWK account relevant for global-level wildlife health reporting (e.g., WAHIS) or biodiversity monitoring (e.g., GBIF) could be shared with these platforms. WOAH's early engagement with HAWK can enhance collaboration and synergies to support interoperability with future WOAH data systems and could help improve current limitations in global wildlife health reporting. The upcoming API will streamline interoperability and expand it to include WHS-relevant information collected or stored in widely distributed tools (e.g., Spatial Monitoring and Reporting Tool, District Health Information Software 2), allowing stakeholders to continue using their primary platforms. By structuring, harmonizing, centralizing, and securing a broader range of WHS information, including data that typically remain scattered, HAWK supports better decision-making within and across organizations, administrative units, or study areas (Fig. 2).

By facilitating WHS data safety, centralization, accessibility, and interoperability, plus its detailed metadata, HAWK supports FAIR and CARE principles compliance. Balance between data protection and availability is achieved by establishing data ownership and by organizations agreeing to comply with self-selected data embargoes, ranging from immediate data availability to obligatory long-term release under open license.

HAWK is powered by WCS, a 130-year old independent nonprofit conservation organization with global presence and a longstanding mission that relies on worldwide distributed funding from public and private sources (https://www.wcs.org/about-us/literature/annual-reports). Through WCS institutional support, HAWK is being developed for long-term sustainability, with data safety and security independent of government regulations, political contexts, or national priorities. If needed, HAWK and its contents can be deployed in any country with Microsoft web services, while remaining under WCS hosting and oversight.

HAWK is a ready-to-adopt global public good, available for any organization in any country, meant to encourage best data practices whose costs can be shared across many parties with funds allocated for data management and storage, alleviating the burden on isolated and resource-limited stakeholders. Critically, **when local funding is unavailable, Global South and Indigenous communities users will have access to HAWK at no charge, within reasonable usage limits**. This approach, together with multilanguage user interfaces and interoperability will foster a global WHS network.

While numerous barriers to WHS remain (e.g., siloed actors, funding, and unclear policy frameworks), HAWK, slated for release in late 2025, aims to fill a historical gap in the availability of a sustainable purpose-built database to support the adequate management of WHS data. We invite the WHS and One Health communities to lay the foundation of their data practices on this database and contribute to its iterative improvement.

## Documentation content

This documentation provides a comprehensive guide to HAWK, covering its data structure (data model), the web-based graphical user interface for general users,  the data dictionary, and the terms of use. Our goal is to offer a clear understanding of HAWK’s organization, functionality, and data semantics.

The documentation is structured as follows:

**Data Model** – A detailed overview of **HAWK's** data structure, enabling users to effectively enter, navigate, and manage data in the database.

**Data Dictionary** – A reference guide listing and describing all data elements, including their names, types, and URIs to their original vocabulary of origin (e.g., the National Agriculture Library Thesaurus, Medical, Medical Subject Headings, and AGROVOC), to ensure consistency, clarity, and interoperability with other systems following these standards.

**Database Manual** – Step-by-step guidance on using the graphical user interface to access, read, write, edit, delete, and manage data.

**Terms of Use** - A comprehensive set of conditions to create a private  **Organization** account, and the terms of use to be accepted prior to the creation of the account, including data embargoes and exceptions for Indigenous peoples.

We hope this documentation helps you maximize **HAWK's** potential. If you have any questions or need assistance, please contact our support team.

