# Introduction {.unnumbered}

WildlifeHealthDat is a versatile database designed to manage wildlife health data collected from various surveillance efforts. These efforts encompass a wide range of activities, including citizen observations of dead, injured, or sick animals, specific research studies, national or local wildlife health surveillance initiatives, outbreak investigations, and global wildlife health surveillance projects involving multiple countries, hazards, and host species

The database draws upon the extensive experience of the Wildlife Conservation Society - Health Program, which spans several decades. This experience includes wildlife health surveillance activities conducted in numerous countries with several public and private partners; both cross-sectional and longitudinal studies; the establishment of wildlife health surveillance networks; investigation of diverse biological, chemical, and physical hazards; research on dangerous zoonotic pathogens like Ebola virus disease and SARS-CoV-2; first detection of emerging vector-borne pathogens such as West Nile virus; engagement of rangers in protected areas and nearby communities as key contributors to health surveillance; logistical challenges related to proper management, storage, and tracking of field-collected specimens; expertise in wildlife pathology; the use and development of various types of diagnostic tests, and prior experience in managing wildlife health data using different information management systems.

The wildlife health information is organized within the database using a structured hierarchy of components, starting from the highest level of "Projects" down to "Surveillance Objectives," "Field Activities," "Locations," "Incidents," "Sources," "Records," "Specimens," and "Diagnostics." While there are four types of sources in the database, it is modular in nature, allowing for customization and selection of specific components based on the requirements of each surveillance initiative. Briefly, Projects are a set of surveillance activities with a common leader and organizer (e.g., a national veterinary services agency). The Surveillance Activity is a surveillance effort that have a specific methodology and objective. The Field Visit represents a period when surveillance activities are conducted. The Location is a specific area where surveillance activities are conducted. An Event is a site where wildlife health surveillance data is collected from. Sources are the units that can present disease and provide specimens for hazard detection or sites where specimens can be collected directly to assess hazards in the environment or in the arthropods. Specimens are the tissue taken from the Sources. Diagnostics are the tests conducted in Animals, Carcasses, or Specimens collected to assess Hazards. Diagnosis are the final status assigned to a Diagnostic, a Specimen, or a Source with respect to the Hazards surveyed based on case definitions. Detailed explanations of each component are provided in the following sections.
