# Location {.unnumbered}

A Location refers to a general place where Events, Source Records, Carcasses, and Specimens can be collected. During a single Field Visit, data may be collected from various Locations, such as two rehabilitation centers, a cave within a protected area, or three different zones within another protected area. In this case, there would be a total of six Locations. Therefore, a Location serves as a way to group data in a more generalized manner compared to the exact latitude and longitude coordinates where data is collected ('Event'; see below), but it provides more specificity than the overall 'Field Activity'. 

What a 'Location' represents will inevitably vary depending on the Surveillance Activity methodology. For example, for the collection of arthropods, a Location can represent a parcel where traps are set. In a structured research, the Location could represent a grid cell. In scanning surveillance by rangers, the Location can correspond to either the full protected area, or the specific zone within the protected area. It is up to the users to define what unit the Location represents and report it in the Surveillance Activity metadata. Locations can be grouped in larger groups below the Field Visit if needed. For a detail explanation, see "Grouping of Locations, Events, and Source Records"