<!-- # Source and Source Records {.unnumbered} -->

### Generalities

A Source in the data model is a unit that can be observed and provide Specimens, including carcasses, organic tissue, abiotic tissue, or arthropods. The data model manages four types of Sources: i) a co-specific group of animals (Group Source), ii) individual animals (Animal Source), iii) sites that can provide abiotic tissue of interest or biotic material of animal origin whose individual or group animal of origin is unknown (Environmental Source), and iv) sites where active or passive collection arthropods at any life stage is completed (Arthropod Source). A Group Source could correspond to a specific bat roost of species X sourcing guano, an Animal Source could be a collared animal, an Environmental Source could be a pond where water is collected from, and an Arthropod Source could be a site where mosquito larvae are collected from. Sources contain time-independent data only, such as the species of an animal in the case of a Group Source or an Animal Source (more below).

All Sources can be individually identified and followed over time. **Animal Sources and Group Sources might not be individually identified preventing following them over time**. 
**All Sources belong to at least one Surveillance Activity** but they can be defined prior to any Event or after. For example, a set of animals can all be individually identified and released before any Field Visit starts. Then, capturing, recapturing, and sampling are conducted in following Field Visits. In that case, these animals are initially Animal Sources in the data model linked to the corresponding Surveillance Activity only. Once the Field Visits begin, all, none, or some of the Sources (rodents) will be part of Events. The Sources that are not part any Event by the end of the Surveillance Activity will still be part of it, but they will not have any data associated with Events, Specimens, Diagnostics, etc. Therefore, **Sources might not be part of any Event**.

Sources that are individually identified during an Event will certainly belong to at least that Event when they were identified and potentially others. For example, a bat (Source) caught in a mist net (Event), identified individually, and recaptured in a following Event. This bat is linked to the capture Event and the recapture Event. 

**Sources that are not individually identified will belong to the Event when they were observed or captured only**. For example, a bat (Source) that is captured and sampled during an Event but not marked or a dead animal found by a ranger during a patrol. The bat and the animal found are linked only to the Event they were capture and observed, respectively.

Sources observed, collected, or captured at time *t* are linked to Events through a **Source Record** (the Source at time *t*). Source Records contain time-dependent data only, such as health status at time *t*. **Sources individually identified can be followed longitudinally and have multiple Source Records that link them to multiple Events over time**.

**An Event can contain any number of Source Records associated with Sources of any type**. For example, an Event can contain Group Source Records, Animal Source Records, Environmental Source Records, and Invertebrate Source Records, two of them, one of them, or three of them. Also remember that **an Event might not contain any Source Record** (e.g., a set up mist net without birds captured).


### Group Source

**A Group Source is a unit of co-specific individuals (animals of the same species) associated to a herd, an area, a site, a farm, a cage, a stall, an enclosure, or another that makes the individuals part a single epidemiological unit**. Group Sources can be observed, captured, and provide Specimens at time *t*. Data of a Group Source include the species, the identifier, the cross identifier, and the date of extinction (see Data Dictionary). 

The purpose of Group Source is to record individuals at health events at the species level instead of individual by individual. This can occur when herds are the unit of interest, when protected area rangers find animals of the same species in a health event, or animals in a unit such as a cage, stall, or vendor of a market. For example, animals of two species in a single cage. If the animals are not meant to be tracked individually, the animals of each species in the cage represent a Group Source. 

#### Group Source Record

**A Group Source Record consists of a count of the animals in the Group Source at time *t*, stratified by sex, age, and health status (e.g., healthy, injured, sick, or dead)**. Other properties of the Group Source Record are observed anomalies, potential causes of disease or death if they apply at time *t* among others (see Data Dictionary). Properties of a Group Source Record are documented at the group level and each property can receive multiple options. For example, a Group Source with three dead animals can receive several potential causes of death. Therefore, **is not possible to know the distribution of several properties across individuals of the Group Source Record**, but only that it was present in at least one individual (the exception is the "species" property and other properties when a Group Source has a single individual). 

**Group Source Records can include a mix of dead, diseased, poisoned, infected, injured, and healthy individuals of the same species or animals of the same species that belong to just one of these categories exclusively (all animals are dead for example)**. A Group Source Record of only healthy animals can also be part of a Health Event depending on the definition of Health Event (e.g., animals of species X with all of them observed healthy next to dead animals of species Y and Z). **Group Source Records can have a single individual**. For example, rangers patrolling a protected area might find a dead animal of species X and two dead animals of species Y at the same site (Event) and rangers record their animal data as Group Sources. If this is the case, the animal of species X belong to a Group Source Record and the animals of species Y correspond to another Source Group Record. Moreover, if only a single animal of a known herd is observed at time *t*, then that individual is the representation of the herd for the Source Group Record. Finally, **an Event can have more than one Group Source Record of the same species**. For example, animals of the same species in two cages hold by a vendor in market where each vendor is considered an Event. Then each cage with the corresponding animals could be considered a unit, and therefore, a Group Source Record belonging to the same vendor (same Event).

An Group Source can be used directly for a Diagnostic (e.g., assessment of fat in carcasses of animals belonging to a specific herd). The data model can accommodate Diagnostics applied to the "group" itself rather than Specimens taken from that Group Source. The diagnostic information is part of the set of Diagnostics conducted in the corresponding Group Source (see Diagnostics).  

**An animal of species X documented as part of a Group Source Record must not be included as an Animal Source Record and vice-versa**. If an Event contains a Group Source Record and an Animal Source Record of species X, then the total number of animals of species X at the Event is the sum of number of animals of species X in the Group Source Record and the single individual of species X recorded as an Animal Source Records. An example is a herd of cows illegally raised in a protected area whose health is assessed at time *t*. The herd of this example contains 20 cows. Two of them are sampled and the rest are part of a single unit. In this case, the sampled cows can be added as Animal Source Records (one per sampled cow) and the remaining 18 animals can be added as a single Group Source Record that distributes the animals per sex, age, and health status. The total number of cows are the individuals in the Group Source Record (18) and the two cows recorded as Animal Records (2). The "herd" identity of the 20 cows can be kept using a "Tag" (see below) so the three Source Records receive the same unit (another option is to add the 20 cows as a Group Source but the data of the specific animals sampled will be lost. See next section). If the Group Source Record contains the original 20 cows and also two Animal Source Records, then the total number of cows will be 22.

### Animal Source

**An Animal Source represents an individual animal whose specific individual-level data is of interest**. Animal Sources can be observed, captured, tested, and provide Specimens at time *t*, including the full carcass to have a Necropsy completed. Animal Source data includes the species, the identifier, the cross identifier, the sex, and the date of death (see Data Dictionary). Past marking codes (if any have been used) are considered immutable and entered as data of an the Animal Source.

An example of Animal Sources are animals of different or the same species in a cage located in a live market. If the data of the animals is to be collected at the individual-level, then each individual represents an Animal Group Source in the cage. 

#### Animal Source Record

**An Animal Source Record consists of an Animal Source at time *t* **. Properties of an Animal Source Record are its age, health status, observed anomalies, and potential cause of disease or death if they apply at time *t*, among others (see Data Dictionary). The marking of an individual animal at time *t* is considered mutable and a property of the corresponding Animal Source Record. Properties of an Animal Source Record can receive single or multiple choices. For example, the observed health status in only one (live healthy, live sick) but an Animal Source Record can receive several observed anomalies if they apply at time *t* (wounded, hair loss, diarrhea, etc. See Data Dictionary).

An Animal Source can be either dead, diseased, poisoned, infected, injured, or healthy at time *t*. **An Animal Source Record with an observed health status "live healthy" can be part of an Event if they are of interest** (e.g., a healthy animal of species X next to dead animals of species X, Y, and Z; healthy animals captured for Specimen collection). 

An Animal Source can be used directly for a Diagnostic (e.g., X-rays in a live animal). The data model can accommodate Diagnostics applied to the "animal" itself rather than a Specimen taken from that Animal Source. The diagnostic information is part of the set of Diagnostics conducted in the corresponding Animal Source (see Diagnostics).  

**An animal of species X documented as part of a Group Source Record cannot be included as an Animal Source Record and vice versa**. If an Event contains a Group Source Record and an Animal Source Record of species X, then the total number of animals of species X at the Event is the sum of number of animals of species X in the Group Source Record and the single individual of species X recorded as an Animal Source Record. An example is a herd of cows illegally raised in a protected area whose health is assessed at time *t*. The herd of this example contains 20 cows. Two of them are sampled and the rest are part of a single unit. In this case, the sampled cows can be added as Animal Source Records (one per sampled cow) and the remaining 18 animals can be added as a single Group Source Record that distributes the animals per sex, age, and health status. The total number of cows are the individuals in the Group Source Record (18) and the two cows recorded as Animal Records (2). The "herd" identity of the 20 cows can be kept using a "Tag" (see below) so the three Source Records receive the same unit (another option is to add the 20 cows as a Group Source but the data of the specific animals sampled will be lost. See next section). If the Group Source Record contains the original 20 cows and also two Animal Source Records, then the total number of cows will be 22.

#### Carcass

The carcass of a dead Animal Source can be used as a source for Specimens and Diagnosis. A Carcass entered to the database comes from a specific Animal Source and they are collected at a single specific time *t*. Therefore, each Carcass is associated with one and only one Animal Source Record (when the Carcass was collected). Properties of a Carcass include its decomposition condition, storage during transport, storage in a facility, and its location (building, room, refrigerator, etc.), among others (see Data Dictionary). The data regarding changes in the storage of the carcass can have many units for the same carcass if it changes over time. 

An carcass can be used directly for a Diagnostic (e.g., X-rays in a dead animal). The data model can accommodate Diagnostics applied to the Carcass itself rather than a Specimen taken from that Carcass (see Diagnostics). The diagnostic information is part of the set of Diagnostics conducted in the corresponding Animal Source. 

##### Necropsy

A Necropsy is associated with a specific Animal Source Record that can occur any date after the corresponding Animal is found dead. However, **a Necropsy is tied to the Carcass**, which is tied to the Animal Source Record when it was collected. **The earliest date a Necropsy can occur is when the dead animal was found and a Field Necropsy was conducted (no Carcass collection) or when the Carcass was collected and used for Necropsy**. Necropsy data includes the identifier, the cross identifier, the date of the necropsy, findings per system, among others (see Data Dictionary).

Necropsies can be primary or secondary. A primary necropsy usually starts with an intact carcass (not previously used in a necropsy). A secondary necropsy is usually conducted by a veterinarian pathologist using pictures of the primary necropsy or using a carcass already necropsied. 

### Environmental Source

**An Environmental Source is a unit in space where Specimens that cannot be associated with a Group Source, an Animal Source, or Arthropod Source can be collected from** (e.g., feces found in the field but unknown individual dropping them or unknown group of animals with the individual that could have dropped them). Properties of an Environmental Source include the type (e.g., water, soil, sediment, air , feces), the species (only for biotic types if it is known), the identifier, and the cross identifier (see Data Dictionary). The species can be either NA (abiotic type such as water, sediment, or soil), "unknown" (e.g., "unknown" for feces found by themselves), or the most accurate taxonomy level that can be given to a biotic Environmental Source if barcoding or another species determination method is not used (e.g., "mammalia" for feces found by themselves). 

#### Environmental Source Record

**An Environmental Source Record is the collected biotic or abiotic tissue from the Environmental Source at time *t* using the same method**. For example, the water obtained from a pond at time *t* across devices targeting water collection. This mean that air collected by any number of devices "X" deployed at the Environmental Source at time *t* to collect air is an Environmental Source Record and air collected by any number of devices "Y" deployed at the Environmental Source at time *t* to collect air is another Environmental Source Record. **A key difference between the Environmental Source and the Group and Animal Sources is that an Event can contain multiple Environmental Source Records of the same Environmental Source (one per collection method) compared with Group and Animal Sources Records types that only have a single Source Record per Source per Event**. The properties of an Environmental Source Record include the identifier, the cross identifier, the volume collected, the unit of the volume collected, among others (see Data Dictionary).

### Arthropod Source

**An Arthropod Source is a unit in space where collection of arthropods can be completed** (e.g., a household in the forest where traps are set). Properties of an Arthropod Source include the identifier, the cross identifier, the area covered, among others (see Data Dictionary).

**If the interest of the Surveillance Activity is at the arthropod individual level (e.g., butterflies with problems in their wings or with parasites), then the user should consider these arthropods as Animal Sources. Arthropods from Animals Sources (attached ticks, lice, fleas, mites) are Specimens from an Animal Source and not Arthropod Sources**.

#### Arthropod Source Record

**An Arthropod Source Record is the collected arthropods from the Arthropod Source at time *t* using the same method**. For example, the number of mosquitoes obtained at the household in the forest at time *t* per species and age-sex-condition across the traps targeting the same group of arthropods. This mean that adult mosquitoes of *n* species collected by any number of CO2 traps deployed at the Arthropod Source at time *t* is an Arthropod Source Record and that adult mosquitoes of *n* species collected by any number of BG traps deployed at the Arthropod Source at time *t* is another Arthropod Source Record. **A key difference between the Arthropod Source and the Group and Animal Sources is that an Event can contain multiple Arthropod Source Records of the same Arthropod Source (one per collection method) compared with Group and Animal Sources Records types that only have a single Source Record per Source per Event**. The properties of an Arthropod Source Record include the identifier, the cross identifier, the species, the age, sex, condition of the females, the corresponding number, among others (see Data Dictionary).

Sources can be clustered in units smaller than Event if needed. For a detailed explanation, see “Clustering of Locations, Events, and Source Records” section below.