<!-- # Specimens {.unnumbered} -->

### Generalities

In the data model, a **Specimen** refer to a sample collected to conduct **Diagnostics** (see "Diagnostics").

**Specimens** originate from the following: 

* Sampled **Group Source Record** (e.g., urine collected under a bat roost and the urine cannot be linked to a specific individual of the roost) and **Animal Source Records** (e.g., an oral swab from an individual animal). These **Specimens** may consist of either a single sample type (e.g., blood) or multiple tissue types (e.g., mixed blood and saliva). 

* Pools of arthropods comprised of the arthropods present at an Arthropod Source Record.

* Samples collected from the environment with abiotic origin (e.g., water) or biotic origin (e.g., feces found in the field)

<!-- * Other **Specimens** (Pooled Specimen). For example, different **Specimens** from the same or multiple **Source Records** are mixed (grey boxes in figure below) with **Diagnostic Products**. In HAWK, a pooled specimen is built from existing **Specimens** records. -->


Key attributes of a **Specimen** include:

* Specimen ID
* Type
* Specimen Original Amount
* Specimen Current Quantity Stored
* Origin
* Ownership


**Specimens** can be stored, and their storage may change multiple times as they are transferred within and between facilities. Similarly, **Specimens** can be shipped multiple times. 

**Specimens** without any amount of tissue left remain in HAWK so the last **Storage**, **Shipment**, and use in **Diagnostics** can be traced.

<!-- ### Specimens of Group Source Records -->

<!-- An example of Group Source Specimen are feces collected from the bottom of a cage with animals of the same species but it is unknown which of the animals dropped the feces.  -->

<!-- **Group Source Specimens cannot be obtained AFTER the last date the Group Source was observed (the last Record of the Group Source)**. For example, it is possible to collect feces from a cage that restrains a **Group Source** longitudinally and also from the same cage after the animals of the **Group Source** were moved. In this case, the **Specimen** from the empty cage does not belong to the **Group Source Record** but to an **Environmental Source Record**. The sampling of the feces from the empty cage belongs to a different **Event**. To keep the connection between the corresponding **Specimens**, it is possible to cluster the **Group Source Records** and the **Environmental Source Record** (see Complexities).  -->

<!-- ### Specimens of Animal Source Records  -->

<!-- An example of Animal Source Specimen is 2 ml of blood taken from a lion.  -->

<!-- **Animal Source Specimens cannot be obtained AFTER the last date the Animal Source was observed (the last Record of the Animal Source)**. For example, it is possible to collect feces from a cage that restrained an Animal Source longitudinally and also from the same cage after the animal was moved. In this case, the **Specimen** from the empty cage does not belong to the **Animal Source Record** but to an **Environmental Source Record**. The sampling of the feces from the empty cage belongs to a different **Event**. To keep the connection between the corresponding **Specimens**, it is possible to cluster the **Animal Source Records** and the **Environmental Source Record** (see Complexities).  -->

<!-- **The data model DOES accept Animal Source Specimens that are CREATED after the last date the Animal Source was documented (the last Record of the Animal Source)**. New **Specimens** can be generated during a **Necropsy** or from a stored **Carcass**. In this case, the date of **Specimen** creation is not necessarily the date when the **Animal Source** was found, when the carcass was collected, or when the animal died, but after the storage of the carcass or the date of the Necropsy. It is possible to track if a **Specimen** was collected in the field (from the animal, carcass, during a field necropsy, or the ground near the animal), or in a facility from the carcass or during a primary or secondary Necropsy based on the information entered for **Specimens**. -->

<!-- ### Specimens from Environmental Source Records  -->

<!-- An example of **Environmental Source Specimen** is 10 grams of soil collected from a landfill (**Environmental Source**). Another useful example are feces of unknown origin found in the field at time *t* (**Source Record**) at a specific site.  -->

<!-- **The data model DOES accept Arthropod Source Specimens that were CREATED after the last date the Arthropod Source was visited (the last Record of the Environmental Source)**. -->

<!-- ### Specimens from Arthropod Source Records  -->

<!-- An example of **Arthropod Source Specimen** is a mosquito pool created from the set of mosquitoes captured at the "Arthropod Source** site at time *t*.  -->

<!-- **The data model DOES accept Arthropod Source Specimens that were CREATED after the last date the Arthropod Source was visited (the last Record of the Environmental Source)**. -->

<!-- ### Specimens with a mix of tissues coming from a unique or several Source Records -->

<!-- A bat is swabbed in its oral cavity and in its rectum but then the swabs are placed together in a tube and considered a single **Specimen**. Then, there is a single **Specimen** with a unique **Source Record** origin and two types of tissue: "rectal swab" and "oral swab" in a tube.  -->

<!-- It is possible also to get blood from two bats and mix it. The data model can accommodate this case because **Specimens can have multiple Source Record origins**. In the example, both bled bats (Source Records) are the origin of a single Specimen with "blood" tissue consisting in mm of blood. -->

<!-- Similarly, **it is possible to generate a Specimen by mixing tissue of different type from different Source Records**. For example, the blood (tissue) of a bat captured at time *t* (**Animal Source Record**) with the feces (tissue) collected from the bottom of the roost of the same bat at time *t* (**Group Source Record**). In this case, the mixed tissue (blood from an Animal Source and Feces from a **Group Source**) can be included in the data model as a single **Specimen** with two Source Records as origin and two types of tissue. -->

<!-- **The key here is that Specimens are generated by mixing tissue coming from different Source Records, which is different than mixing Specimens**. In the data model, mixing **Specimens** means mixing data Units already documented (see "Pooled Specimens" below).  -->

<!-- ### Specimens from Diagnostic Products -->

<!-- Products generated by a **Diagnostic** method (see **Diagnostic Products** as **Specimens** below) can be stored and used as **Specimen** in further **Diagnostics** (e.g., use cDNA created as part of Diagnostic A used in a new RT-PCR, Diagnostic B). The data model can accommodate Diagnostic Products to be used as **Specimens** in future **Diagnostics**. In this case, the origin of these new "Specimens" are specific Diagnostics and not **Source Records**, and their type is a diagnostic product such as cDNA. The remaining properties of a **Specimen** from a Diagnostic Product are the same as for **Specimens** from **Source Records** (see Data Dictionary). -->

<!-- Diagnostic Products must be added to the data model as a **Specimen**, so it can have **Diagnostics** and be pooled with other **Specimens**. -->

### Pooled Specimens (under construction)

<!-- **Specimens** can be created by mixing other **Specimens** of any origin. For example, mixing a **Specimen** from an **Arthropod Source**, a **Specimen** from an **Animal Source**, a **Specimen** from an **Environmental Source**, and a **Specimen** from an **Arthropod Source** (see below). The origin of Pooled Specimens is tracked in the data model. In the example, the origin of the **Specimen** is four **Specimens** and the new **Specimen** has potentially four types of tissue. The remaining properties are the same as for **Specimens** from **Source Records** (see Data Dictionary).  -->

### Specimens in Containers

In situations where space or materials are limited, it is possible that multiple **Specimens** are stored in a unique container. This approach is clearly not ideal because it can lead to cross-contamination and make actual **Specimen** tracing more complex. However, the data model has a Container Identifier as a **Specimen** property (see Data Dictionary). Specific properties for each individual **Specimen** within the container, such as type, quantity, etc, should allow their visual identification within the container.


