# Surveillance Objective {.unnumbered}

A Surveillance Objective refers to a set of activities established to collect data with the aim of detecting, quantifying, or assessing trends related to specific health hazards within specific populations, using a standardized methodology. Each Surveillance Objective should specify the target populations, hazard, Source and Specimen collection methods, and Diagnostics. For example, a capture-mark-recapture study targeting lead accumulation in a specific vulture population involving the collection of blood samples and conducting tests using the same Diagnostic for every capture.

Surveillance Objectives include targeted surveillance and scanning surveillance initiatives and they are the most complex component of the database, so it is essential to read this section carefully.

Surveillance Objectives include detailed metadata that describe their objectives and methods. This metadata includes information on the targeted species, populations, and hazards, as well as the types of Sources and Specimens included, collection methods, and case definitions for specific Diagnostics, Specimens, and Sources. Some metadata elements are provided for each Source type, such as Observation, Animal Source, Environmental Source, and Invertebrate Source (see next sections).

Typically, Field Activities, Locations, Incidents, Sources, Records, and Diagnostics belong to a single Surveillance Objective. This Surveillance Objective is the one that initially requested Field Activities at different Locations to record Incidents, collect Sources and Specimens, and perform Diagnostics for a specific hazard. In such cases, the Surveillance Objective is automatically assigned to each corresponding component.

However, there are exceptions to this rule, except for Diagnostics, which have different justifications for each component. Field Activities, Locations, Incidents, Source Records, and Specimens can be originally requested by different Surveillance Objectives planning the same activities and methods but targeting different hazards. For example, rodents trapped in the same Incidents may be sampled using the same methodology and tested for both coronaviruses and Rickettsia sp (two Surveillance Objectives). In this scenario, only one of the Surveillance Objectives will be automatically assigned. It is the user's responsibility to add the second Surveillance Objective to the corresponding Field Activities, Locations, Incidents, Source Records, and Specimens.

Another exception occurs when Source Records and Specimens collected during past surveillance efforts are included in future surveillance initiatives. For instance, using pangolin Specimens collected by rangers patrolling a protected area in 2017 as part of a scanning surveillance strategy, which are then tested in 2023 for SARS-CoV-2 as part of a targeted surveillance initiative. In this case, the latter Surveillance Objective does not generate new Field Activities, Locations, or Incidents, but the Specimens tested for SARS-CoV-2 and their Sources will have multiple Surveillance Objectives. One corresponds to the original Surveillance Objective that mandated the Field Activity for collecting the Source Records and Specimens, and the other is the new Surveillance Objective targeting SARS-CoV-2.

Moreover, new Necropsies might be conducted during the Surveillance Objective targeting SARS-CoV-2, new Specimens could be created (from larger stored Specimens, such as a carcass or an organ), or new Pooled Specimens could be produced. All these components receive the Surveillance Objective targeting SARS-CoV-2 only. Again, it is the user's responsibility to add the second Surveillance Objective to the new Source Records and Specimens.

Each diagnostic remains linked to a single Surveillance Objective (new Diagnostics targeting SARS-CoV-2 will be associated with the SARS-CoV-2-related Surveillance Objective exclusively). Surveillance Objectives added to a Diagnostic will be automatically assigned to the corresponding Specimen, Source Record, and Source.

Therefore, Surveillance Objectives can be interconnected for various reasons, such as belonging to the same Project, sharing common Field Activities, Locations, and Incidents, or having common Sources and Specimens. If Surveillance Objectives are connected for the latter two reasons, then these connections must be specified in the metadata of the corresponding Surveillance Objectives. These connections will also be evident in the exported data, where each component with multiple Surveillance Objectives (e.g., Field Activity, Specimen) will be represented by one row per Surveillance Objective.

## Outbreak Investigation

All outbreak investigations are considered Surveillance Objectives, although the information regarding the outbreak (name and diagnosis) can be provided after the creation of the Surveillance Objective in the database.
