

## PROJECT

It is a surveillance initiative supported by specific entities. For example,
the PREDICT Project funded by USAID, an isolated cross-sectional study with a 
single field visit to a single location (sample collection in a market), or 
a national or local wildlife health surveillance network lead by a
government agency. Projects are the highest hierarchical unit in the database 
and they contain at least one surveillance objective. 

## SURVEILLANCE OBJECTIVE

It is a set of activities established to collect data in order to detect, quantify, 
or assess trends regarding specific health hazards in specific populations under a
common methodology. Each Surveillance Objective should have a specific population
and hazard target, Source or Specimen Collection methods, and Diagnostics. For 
example, a capture-mark-recapture study targeting lead accumulation in a specific
population of vultures that involves blood collection and testing at every capture
using the same diagnostic technique. Surveillance Objective is the most complicated
component of the database. Read this section carefully.

Surveillance Objectives contain very specific metadata, describing their goals and 
methods used, including targeted species, populations, and hazards; the type of 
Sources and Specimens included; collection methods; and case definitions for 
specific Diagnostics, Specimens, and Sources. Some pieces of the metadata are provided 
by Source type (Observation, Animal Source, Environmental Source, and Invertebrate
Source, [see below]).

Surveillance Objectives apply for targeted surveillance and scanning surveillance
initiatives so both types can be described through the metadata. All Outbreak 
Investigations are a Surveillance Objective, although the outbreak information 
(name and diagnosis) can be provided later and not immediately after the Surveillance
Objective creation in the database.


Usually, Field Activities, Locations, Incidents, Sources, Records, and Diagnostics
belong to a single Surveillance Objective. This Surveillance Objective
is the one that originally requested the Field Activity at different Locations to 
record the corresponding Incidents, collect the Sources and Specimens, and perform 
Diagnostics for a specific hazard. In this case, the Surveillance Objective is 
provided automatically to each corresponding component.

However, there are exceptions to this rule, except for Diagnostics, and the exceptions
have different justifications for each component. Field Activities, Locations,
Incidents, Source Records, and Specimens can be originally requested by different 
Surveillance Objectives planning the same activities and methods but that differ 
in the targeted hazard. For example, rodents sampled using the same methodology
that will be tested for Coronaviruses and Rickettsia sp. It is the user responsibility
to add the second Surveillance Objective to the corresponding Field Activities, 
Locations, Incidents, Source Records, and Specimens.

Another exception can occur when Source Records and Specimens collected under
scanning surveillance efforts are included in future targeted surveillance initiatives.
For example, using pangolin Specimens collected by rangers patrolling a protected 
area in 2017 under a scanning surveillance strategy that are  tested in 2023 for
SARS-CoV-2 as part of a targeted surveillance initiative. In this case, the 
corresponding Specimens tested for SARS-CoV-2 and their Sources will have more than
one Surveillance Objective. The one that originally demanded conducting the Field
Activity to collect the Source Record and Specimens, and the new Surveillance 
Objective targeting SARS-CoV-2. This last Surveillance Objective [DOES NOT]{.underline}
generate new Field Activities, Locations, or Incidents. Finally, each Diagnostic 
remains having a single Surveillance Objective (new Diagnostics targeting 
SARS-CoV-2 receive the SARS-CoV-2-related Surveillance Objective only).

Moreover, during Surveillance Objective targeting SARS-CoV-2 new Necropsies might
be conducted, new Specimens could be created (from larger stored Specimens, such
as a carcass or an organ), or new Pooled Specimens could be produced. All these 
components receive the Surveillance Objective targeting SARS-CoV-2 only. Again,
it is the user responsibility secondary Surveillance Objective to the corresponding
Source Records, Specimens and Diagnostics.

Therefore, a Surveillance Objective can be linked to others because they belong
to the same Project; they requested the same Field Activities, Locations, 
and  Incidents; or they have Sources and Specimens in common. If Surveillance 
Objectives are connected for the second and third reason, then this connection must
be provided in the metadata of the corresponding Surveillance Objectives. The 
connections will be also evident in the exported data such that each component with
more than one Surveillance Objective (Field Activity,..., Specimens) will be
represented by one row per Surveillance Objective.


## FIELD ACTIVITY

A Field Activity correspond to a field visit with a start and end date. Each one 
of these Field Visits could involve more than one Surveillance Objective (see above)
and Locations (see below) of different types such as markets, natural areas, 
rehabilitation centers, caves, etc.

## LOCATIONS

A Location is a general place where Incidents, Source Records, and Specimens are
collected. For example, a single Field Visit could involve different places: 
two rehabilitation centers, one cave in a protected area, and  three areas of another
protected area. These examples include six Locations. A Location groups data in a
more general manner than the exact longitude and latitude of the data collection 
(see 'Incidents' below that contain the latitude and longitude information) 
but that is more specific than 'Field Activity'. 

In the examples provided in the previous paragraph, a 'market' could be a 'Location'
or an 'Incident' by itself (see below) depending on what the user considers the 
best choice for the corresponding Surveillance Objective. More detail about what an
Incident represents is provided in the next section.

## INCIDENTS

An Incident is a specific wildlife health event at specific longitude and latitude
and that occurs in a specific date.

The definition of what a wildlife health event (and therefore of the 'Incident'
component) depends on the Surveillance Objective methodology. In targeted surveillance
efforts, an Incident could imply just healthy animals sampled in a specific 
time-space unit to test them for the targeted hazard. Non-sampled individuals,
injured, sick, or dead may or may not be included as part of the Incident. 
If samples are collected from a river, then the 'Incident' can be equivalent to
the location where water is extracted at. For the surveillance of vector-borne 
diseases, an 'Incident' could be a point in time and space where one to several
traps for vectors have been placed. For scanning surveillance, an 'Incident' could
require the presence of at least one injured, sick, or dead animal, or an stranded
individual. The 'Incident' can also include the healthy individuals found nearby.

In the case of beached fish, an Incident could represent each dead fish 
in one extreme. On the other extreme an Incident can represent to the full count
of dead fish across the beach as a single point in time and space. None of these
strategies seem ideal. The former, for logistic purposes and the latter, for the 
loss of valuable information (distribution of the dead fish across the beach). 
So an Incident should represent a unit in between. 

Similarly, an entire market could represent a 'Location' and a single 'Incident' 
at the same time. This Incident can gather data from several vendors, cages, and
animals within cages. On the other hand, a market could be a 'Location' and each
vendor within the market could be an 'Incident'. Finally, a structured
study can involve several levels of hierarchy and one of them receives the 
temporo-spatial coordinate. Another similar structured study (zone, 
grid, area, trap, etc.) might provide the spatial coordinate to a different unit 
(for example the area in one case and the trap in another case). Therefore, 
an Incident can represent a wide range of units depending on the methodology used
to record health ata. For this reason, it is necessary to provide flexibility to what
an Incident is per surveillance design and it is also necessary to request and 
explicitly declare what an Incident represents as part of its data.

In the market example or structured studies, it could be desired to group Incidents
more specifically than under the general 'Location'. For example, a market can be
a 'Location' and each cage could represent an 'Incident'. It is possible that users
want to group cages by vendors and vendors by area within the market, Similarly,
it is possible that in a structured study the 'Incident' represents a trap, and 
the researchers want to group traps these Incidents by area, grid cell, zone, and
season. For this reason, the database contains several 'Incident' tags to group 
them temporally, spatially, or both in a finer scale than Location. Specific tags
can be requested by users.

Incidents must have at least one Source Record from one Source type (see below) 
and as many Source Records of any type as needed (depending on what is found/recorded
in each specific Incident and what is the interest of the corresponding Surveillance 
Objective).

## SOURCES AND SOURCE RECORDS

A Source is an entity of interest within each Incident from which health information
is collected or generated. There are four classes of Sources with different properties:
Observations, Animal Source, Environmental Source, and Invertebrate Source (see below
for a full description of each type). Following the modular properties of the 
database, the Source types become available depending on the Surveillance Objective
methods and goals per user request.

Each Source contains at least one Source Record (Source recorded at time t). 
Depending on the type, a Source can be recorded multiple times (several Source
Records). For example, a capture-mark-recapture study with animals bled and tested
at each capture instance. Obviously, the first time a Source is entered in the 
database corresponds to its first Source Record.

A Source has immutable information over time. A Source Record has information 
of a specific Source that is mutable over time. Most Sources can provide
Specimens such as full carcasses, body parts, fluids, tumors, blood, water, sediment,
invertebrates, etc. These Specimens can be obtained during any of the Source Records 
of the corresponding Source.

Observations provide only a single Source Record (see below). Animal Sources, 
Environmental Sources, and Invertebrate Sources can provide as many Source Records
as needed. 

### Observation

An Observation corresponds to [observed-only animal(s)]{.underline} present at one 
Incident [grouped by species]{.underline}. For example, a wildlife health event 
involving a single isolated injured animal. If this individual is 
observed only, then the Incident has a single Observation representing a single 
species. The animal count for that single species is one. 

Another example: five animals are found in a wetland, two of them of species "A" 
and three of them of species "B". One animal of species "A" is sick. If they are
only observed and the Surveillance Objective is not interested in individual 
animal-level data,then this set of findings is a wildlife health 'Incident' with
two 'Observations'. One 'Observation' represents species "A" (one healthy individual
and one sick animal), and another 'Observation' represents species "B" (three 
healthy individuals).

Incidents can include Observations (species) with healthy animals only, as long
as they are part of a wildlife health event.

Each Observation generates one and only one Source Record with immutable data. 
In that unique Source Record animals are categorized by sex, age and health status.
The captivity categories of the corresponding animals; their anomalies; and potential
causes of injury, disease, or dead can be provided.

If the same set of only-observed animals are believed to be found five days latter,
then a new Observation must be created because there is not certainty that they 
are the same individuals. If users want to track the animals longitudinally, 
they should be added singly to the database as 'Animal Source' (see below).

### Animal Source

An Animal Source represents an individual animal. Animal Sources 
can be added because the Surveillance Objective aims to collect individual-level
health information (e.g., individual findings in stranded pilot whales), because 
the Animal Sources provide Specimens to perform Diagnostics or to be stored (carcass,
body part, tissue, organs, samples, etc), or because a Diagnostic is conducted in
individual animals that do not necessarily provide Specimens (e.g., evident hair
loss in a free-ranging red fox). 

Immutable data of Animal Sources are the sex, the species, and the date of death.
Previous marking codes (if any has been used) are immutable; however, current marking
codes are considered mutable and are provided in the corresponding Animal Source
Record (see below).

##### Animal Source Record

Each Animal Source has at least one Source Record. This first Source Record corresponds
to the unique record of an unidentified individual animal or to the first record
of an individually identified animal. Individually identified animals can potentially
be tracked over time and have as many Source Records as needed.  

Mutable data of an Animal Source over time needs to be provided for each Source
Record. Mutable data includes the captivity category, the health status, the age,
and the marking code. These are one option features per Animal Source Record.
Other mutable data for Animal Sources that can have multiple values in each Animal
Source record are the anomalies found and the potential causes of injury, disease,
or death. Obviously, the time t when the Animal Source is recorded is also mutable.

The last Animal Source Record for an animal is not necessarily the last time t when
it was found dead because it is possible to collect Specimens from the carcass (dead 
Animal Source) over a period of time while the carcass is rooting. 

##### Necropsies

Necropsies are associated with the specific Animal Source Record when the carcass
was collected. However, the Necropsy date can be any date since the corresponding
Animal Source Record creation.

Necropsies can be primary or secondary. Primary necropsies usually start with an
intact carcass (not previously used in a necropsy). Secondary necropsies are usually
conducted by a veterinarian pathologist using pictures of the primary necropsy or
using a carcass already necropsied.

New Specimens can be generated during a Necropsy (e.g., samples from organs). In 
this case the date of Specimen collection is not the date of the  Animal Source 
Record when the carcass was collected, but the date of the Necropsy (primary or 
secondary). It is possible to track if a Specimen was collected during the 
primary or secondary Necropsy based on the information collected in Specimens 
(see below).

### Environmental Sources

An Environmental Source represents an entity that provides Specimens that: i) 
are abiotic (e.g., a location of a frozen pond that is sampled for Avian influenza), 
or ii) are biotic but it is not possible to identify the corresponding Animal Source
(e.g., feces found in the field). Environmental Sources do not have sex or date 
of death.

Immutable data of Environmental Sources are the species (in the case of type of 
biotic Environmental Sources) and the Environmental Source type. Setting the 
Environmental Source type determines the Specimen type provided for those Sources
(see 'Specimens' below). For example, feces can only yield feces as Specimens, 
and water in a pond can only provide water. 

##### Environmental Source Record

Each Environmental Source has at least one Source Record. This first Source Record
corresponds to the unique collection from an unidentified Environmental Source (e.g., 
feces on the ground) or to the first record of an individually identified 
Environmental Source (e.g., water collected at a specific place in the
pond). Individually Environmental Sources can potentially be tracked over time 
and have as many Source Records as needed.  

Environmental Sources do not have mutable data except the time t when they are sampled.

### Invertebrate Sources

An Invertebrate Source is an invertebrate trap (e.g., CO2 traps, flag
traps, etc.) placed in specific coordinates Invertebrate Sources can be added 
because the Surveillance Objective aims to collect invertebrates and potentially
test them for vector-borne diseases. 

The only immutable data of Invertebrate Sources is the trap. If the same type of
trap is placed in the same coordinates, then Invertebrate Sources can be tracked
longitudinally; however, the invertebrate species collected each time the trap is 
set can be different. Invertebrate Sources do not have sex, age, captivity category,
anomalies, health status, potential cause of death, etc.

Invertebrate Sources are designed to contain data of a collection of invertebrates. 
If the interest is at the individual level (e.g., bees with problems in their wings),
then the user should add Animal Sources.

##### Invertebrate Source Record

Each Invertebrate Source has at least one Source Record. This first Source Record
corresponds to setting the type of trap in specific coordinates. As mentioned in
the previous section, if the same type of invertebrate trap is placed in the same
coordinates, then Invertebrate Sources can be tracked over time and have as many
Source Records as needed. If the type of trap changes, then it is a different 
Invertebrate Source.

Mutable data of an Invertebrate Sources needs to be provided for each Source
Record. The mutable data of Invertebrate Sources is the species captured (probably
more than one). Obviously, the time t when the Invertebrate Source is recorded is
also mutable.

## FINAL COMMENT ON SOURCES AND SOURCE RECORDS

Users can group Source Records from different Sources beyond the Incident
they belong to. For example, a Surveillance Objective design involves sampling
animals and cages in a market as part of targeted surveillance efforts. One of 
the potential options to structure these data is to set the market as the Location
and set each vendor within the market as an 'Incident'. Let's pretend that in one of
the Incidents (a vendor) a sample of feces is collected from the bottom of a cage,
the cage has three animals of the same species, and only one of those animals is 
sampled (one oral swab sample). 

Under this scenario, the cage is providing three Source Records. Firstly, an 
Environmental Source with a single Environmental Source Record containing the feces
sampled from the bottom of the cage. Secondly, an Observation with the two animals 
in the cage that are only observed (Observations always have a single Record). 
And thirdly, an Animal Source with a single Animal Source Record containing the
oral swab. 

How to track that these Source Records belong to the same cage? The database provide
tags per user request that allow to label Sources Records that belong to units lower
than Incidents and keep them linked in the data. In the example, the three Source
Records can receive the same tag ("cage1") in order to track that they have a more
specific origin than Incident.

## SPECIMENS

Specimens correspond to material collected from Source Records to conduct Diagnostics
in order to identify hazards (Biological, Chemical, Physical) or Physiological
problems. The material collected can range from the full body to conduct an ultrasound
in a live animal up to a trace of tissue to perform a highly technological assay.
Invertebrate Source Records can have multiple species; however, it is expected that
their Specimens do contain invertebrates belonging to the same species.

Specimens are characterized by an identifier, the type of material (water, hair,
kidney, animal), the original amount (e.g., 'full animal' or 0.35 mm), the solution
used to maintain them, and their storage type in the laboratory. Moreover, the 
database tracks the Specimen location (building, laboratory name, refrigerator 
name, etc), their availability, ownership, and current amount. The original amount
and the current amount can differ if certain quantity of the original Specimen has
already been used for previous Diagnostics.

Animal Specimens that are equivalent to the Animal Source Record (both are the 
'full animal') must be given information at the Source Record level and at the 
Specimen level. The Source Record and Specimen could have the same identifier or
a different one. The amount of the Specimen in those cases should be 'full animal'. 

Specimens whose current amount is zero must not be deleted from the database and 
their last location should remain.

It is possible that for lack of space or materials, more than one Specimen is stored
in the same container. This strategy can cause cross contamination and make Specimen
tracing more complicated. For this reason, Specimens can have a 'Container' identifier
that is the same among Specimens sharing the same container. Although Specimens
within the same container might not be labeled individually, a unique Specimen 
identifier must be provided in the database. This identifier can be the same as
the container identifier plus an "organ name" or a numeric string at the end: 
".1", ".2", etc. A description of each specific 'Specimen' within the container 
can be provided in 'Comments' allowing the identification of each tissue in the 
container as the corresponding Specimen.


